device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'

concurrency: 12
fixed_depth: 8
data_write_path: '/media/connor/7F35A067038168A9/seer_train3/data.txt'
tt_mb_size: 8192
target_sample_count: 300000000

data_read_paths: ['/media/connor/7F35A067038168A9/seer_train3/data.txt', '/media/connor/7F35A067038168A9/seer_train3/terashuf/data_shuf.txt']


epochs: 100000
shuffle_buffer_size: 200000

mirror_probability: 0.48
batch_size: 2048

visual_directory: 'visual'

save_rate: 1024
report_rate: 50
test_rate: 50
max_queue_size: 128

gamma: 0.05
step_size: 100

learning_rate: 0.07
